spring:
  redis:
    database: 0
    host: 81.71.119.229
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 8
    jedis:
      pool:
        max-wait: -1
        max-idle: 8
        min-idle: 0