server:
  port: 8081
  shutdown: graceful

############ 日志配置 ############
logging:
  config: classpath:logback.xml

############ Spring配置 ############
spring:
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://81.71.119.229:3306/jack_gen?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai&useSSL=false
      username: root
      password: 123456
      #配置监控统计拦截的filters，去掉后监控界面SQL无法进行统计，wall用于防火墙
      filters: stat,wall,config
      #最大支持连接数
      max-active: 100
      #最小连接数
      min-idle: 10
      #初始化大小
      initial-size: 10
      #获取连接等待超时时间
      max-wait: 600000
      #间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 600000
      #一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      #验证连接有效SQL
      validation-query: select 'x'
      #申请连接时执行validationQuery检测连接是否有效
      test-on-borrow: false
      #归还连接时执行validationQuery检测连接是否有效
      test-on-return: false
      #如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效
      test-while-idle: true
      #开启缓存
      pool-prepared-statements: true
      #指定每个连接上PSCache的大小
      max-pool-prepared-statement-per-connection-size: 20
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 5000
      stat-view-servlet:
        enabled: true
        login-username: root
        login-password: 123456
        allow: 172.16.48.30
  application:
    name: gen

############ Mybaits-plus配置 ############
mybatis-plus:
  # MyBatis Mapper所对应的XML文件位置
  mapper-locations: classpath:/mapper/**/*Mapper.xml
  global-config:
    # 自动刷新Mapper对应的XML文件
    refresh: true
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      # 主键类型 0:数据库ID自增 1.未定义 2.用户输入 3 id_worker 4.uuid 5.id_worker字符串表示
      id-type: ASSIGN_ID
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: not_empty
      # 默认数据库表下划线命名
      table-underline: true
      # 逻辑删除配置
      # 逻辑删除全局值（1表示已删除，这也是Mybatis Plus的默认配置）
      logic-delete-value: 1
      # 逻辑未删除全局值（0表示未删除，这也是Mybatis Plus的默认配置）
      logic-not-delete-value: 0
    # 机器ID(雪花算法)
    worker-id: 1
    # 数据表示(雪花算法)
    datacenter-id: 1
  configuration:
    map-underscore-to-camel-case: true
    # 打印SQL，生产环境应当注释掉
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

swagger:
  enable: true
  application-name: 平台代码
  application-version: 1.0
  application-description: 平台代码
