server:
  port: 8888
spring:
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://81.71.119.229:3306/jack_admin?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai&useSSL=false
      username: root
      password: 123456
      #配置监控统计拦截的filters，去掉后监控界面SQL无法进行统计，wall用于防火墙
      filters: stat,wall,config
      #最大支持连接数
      max-active: 100
      #最小连接数
      min-idle: 10
      #初始化大小
      initial-size: 10
      #获取连接等待超时时间
      max-wait: 600000
      #间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 600000
      #一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      #验证连接有效SQL
      validation-query: select 'x'
      #申请连接时执行validationQuery检测连接是否有效
      test-on-borrow: false
      #归还连接时执行validationQuery检测连接是否有效
      test-on-return: false
      #如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效
      test-while-idle: true
      #开启缓存
      pool-prepared-statements: true
      #指定每个连接上PSCache的大小
      max-pool-prepared-statement-per-connection-size: 20
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 5000
      stat-view-servlet:
        enabled: true
        login-username: root
        login-password: 123456
        allow: 172.16.48.30
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*Mapper.xml
swagger:
  enable: true
  application-name: 平台基础
  application-version: 1.0
  application-description: 平台基础